Repository ashitagaur00/HappyOCT, pull requests merged in 2022-10, with the labels that each got.

#1 Created basic.js
  basics.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#3 File added
  Regular expressions
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#5 Updated Regular Expression file
  Regular expressions
Labels: hacktoberfest-accepted, hacktoberfest

#4 Update index.js
  index.js
Labels: hacktoberfest-accepted, hacktoberfest

#7 Create pwa.js
  pwa.js
Labels: hacktoberfest-accepted, hacktoberfest

#8 Update index.js
  index.js
Labels: hacktoberfest-accepted, hacktoberfest

#9 Update pwa.js
  pwa.js
Labels: hacktoberfest-accepted, hacktoberfest

#12 Create SelectionSort.js
  SelectionSort.js
Labels: hacktoberfest-accepted

#14 Create BucketSort.js
  BucketSort.js
Labels: hacktoberfest-accepted
